name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mssql-lambda

    - name: Create Container from Image
      run: docker run --rm --volume $(pwd):/tmp mssql-lambda cp /layer.zip /tmp/

    - name: Upload layer artifact
      uses: actions/upload-artifact@v4
      with:
        name: pyodbc-layer
        path: layer.zip

    # - name: Copy ZIP file from Container
    #   run: docker cp temp-container:/layer.zip ./layer.zip

    # - name: Upload Release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: layer.zip
    #     tag_name: ${{ github.ref }}