name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mssql-lambda

    - name: Create Container from Image
      run: docker run --rm --volume $(pwd):/tmp mssql-lambda cp /layer.zip /tmp/

    - name: Upload layer artifact
      uses: actions/upload-artifact@v4
      with:
        name: pyodbc-layer
        path: pyodbc-mssql-python312-x86_64.zip

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: pyodbc-mssql-python312-x86_64.zip
        tag: ${{ github.ref }}

    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: Release ${{ github.ref }}
    #     draft: false
    #     prerelease: false